mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stores/',include("stores.urls",namespace="stores")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stores/urls.py
from django.urls import path, include, re_path
from stores.views import index, products, detail, results, StoreCreate, ProductCreate, StoreUpdate, ProductUpdate, StoreDelete, ProductDelete, contact, UserFormView, login_user, logout_user

app_name = "stores"
urlpatterns = [
    path('', index, name='index'),
    re_path(r'^(?P<store_id>[0-9]+)/$', detail, name='detail'),
    re_path(r'^st_add/$', StoreCreate.as_view(), name='store-add'),
    re_path(r'^st_addproduct/$', ProductCreate.as_view(), name='product-add'),
    re_path(r'^store/(?P<pk>[0-9]+)/$', StoreUpdate.as_view(), name='store-update'),
    re_path(r'^product/(?P<pk>[0-9]+)/$', ProductUpdate.as_view(), name='product-update'),
    re_path(r'^store/(?P<pk>[0-9]+)/delete/$', StoreDelete.as_view(), name='store-delete'),
    re_path(r'^product/(?P<pk>[0-9]+)/delete/$', ProductDelete.as_view(), name='product-delete'),
    re_path(r'^results/$',results,name='results'),
    re_path(r'^products/$',products,name='products'),
    re_path(r'^contact/$',contact,name='contact'),
    re_path(r'^register/$',UserFormView.as_view(),name='register'),
    re_path(r'^login_user/$',login_user,name='login_user'),
    re_path(r'^logout_user/$',logout_user,name='logout_user'),
]

stores/models.py
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import Permission, User

# Create your models here.

class Store(models.Model):
    id = models.CharField(max_length=9,primary_key=True)
    description =  models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    store_pic = models.FileField(null=True)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

    def __str__(self):
        return(self.id+" "+self.description+" "+self.address)

    def get_absolute_url(self):
        return reverse('stores:index')

class Product(models.Model):
    store = models.ForeignKey(Store,on_delete=models.CASCADE)
    description = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10,decimal_places=2)

    def __str__(self):
        return(self.id+" "+self.description+" "+self.price)

    def get_absolute_url(self):
        return reverse('stores:products')

stores/forms.py
from django import forms
from django.contrib.auth.models import User

class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(required=True,widget=forms.Textarea)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)	
    
    class Meta:
        model = User
        fields = ['username','email','password']

stores/views.py
from django.shortcuts import render
from django.http import HttpResponse  
from stores.models import Store, Product
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.db.models import Q
from stores.forms import ContactForm
from django.shortcuts import redirect
import smtplib
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .forms import UserForm
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

def index(request):
   if not request.user.is_authenticated:
    return render(request, 'login.html')
   else:
    all_stores = Store.objects.filter(user=request.user)
    context = {'all_stores':all_stores}
    return render(request,'index.html',context)

def products(request):
   if not request.user.is_authenticated:
    return render(request, 'login.html')
   else:
    all_products = Product.objects.all()
    context = {'all_products':all_products}
    return render(request,'products.html',context)

def detail(request,store_id):
  if not request.user.is_authenticated:
    return render(request, 'login.html')
  else:   
    my_store = Store.objects.get(pk=store_id)
    if my_store.user == request.user:
        store_product = Product.objects.filter(store=my_store)
        context = {'store_product':store_product,'my_store':my_store}
        return render(request,'detail.html',context)
    else:
        all_stores = Store.objects.filter(user=request.user)
        context = {'all_stores':all_stores}
        return render(request,'index.html',context)

class StoreCreate(LoginRequiredMixin, CreateView):
  login_url = '/stores/login_user/'
  model = Store
  fields = ['id','description','address','store_pic']
  
  def form_valid(self, form):
      obj = form.save(commit=False)
      obj.user = self.request.user
      obj.save()
      all_stores = Store.objects.filter(user=self.request.user)
      context = {'all_stores':all_stores}
      return render(self.request,'index.html',context)

class ProductCreate(LoginRequiredMixin, CreateView):
  login_url = '/stores/login_user/'
  model = Product
  fields = ['description','price','store']
  
  def form_valid(self, form):
      obj = form.save(commit=False)
      obj.user = self.request.user
      obj.save()
      all_stores = Store.objects.filter(user=self.request.user)
      context = {'all_stores':all_stores}
      return render(self.request,'index.html',context)

class StoreUpdate(LoginRequiredMixin, UpdateView):
  login_url = '/stores/login_user/'
  model = Store
  fields = ['id','description','address','store_pic']
  def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user == request.user:
            return super(UpdateView, self).get(request, *args, **kwargs)
        else:
           all_stores = Store.objects.filter(user=request.user)
           context = {'all_stores':all_stores}
           return render(request,'index.html',context)

class ProductUpdate(LoginRequiredMixin, UpdateView):
  login_url = '/stores/login_user/'
  model = Product
  fields = ['description','price','store']
  def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.get_object():
            return super(UpdateView, self).get(request, *args, **kwargs)
        else:
           all_products = Product.objects.all()
           context = {'all_products':all_products}
           return render(request,'products.html',context)

class StoreDelete(LoginRequiredMixin, DeleteView):
    login_url = '/stores/login_user/'
    model = Store

    def delete(self, request, *args, **kwargs):
       self.object = self.get_object()
       if self.object.user == request.user:
          self.object.delete()
       all_stores = Store.objects.filter(user=request.user)
       context = {'all_stores':all_stores}
       return render(request,'index.html',context)

class ProductDelete(LoginRequiredMixin, DeleteView):
    login_url = '/stores/login_user/'
    model = Product

    def delete(self, request, *args, **kwargs):
       self.object = self.get_object()
       self.object.delete()
       all_products = Product.objects.all()
       context = {'all_products':all_products}
       return render(request,'products.html',context)       
 
def results(request):
   if not request.user.is_authenticated:
    return render(request, 'login.html')
   else:
    all_stores = Store.objects.all()
    if request.method == 'GET':  # If the form is submitted
        search_query = request.GET.get("q")
        all_stores = all_stores.filter((
            Q(id__icontains=search_query) |
            Q(description__icontains=search_query)) &
            Q(user=request.user)).distinct()
    context = {'all_stores':all_stores}
    return render(request,'index.html',context)

def contact(request):
   if not request.user.is_authenticated:
    return render(request, 'login.html')
   else:
    form_class = ContactForm
    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get(
                'contact_name'
            , '')
            contact_email = request.POST.get(
                'contact_email'
            , '')
            form_content = request.POST.get('content', '')
            sender = 'scripts@itesm.edu'
            receivers = ['scripts@itesm.edu']
            message = """From: Stores application <scripts@itesm.edu>
To: <scripts@itesm.edu>
Subject: Stores contact message

Contact name: """ + contact_name + "\n" + "Contact email: " + contact_email + \
                         "\nMessage contents: \n" + form_content   

            smtpObj = smtplib.SMTP('localhost')
            smtpObj.sendmail(sender, receivers, message.encode("utf-8"))         
            return redirect('stores:index')

    context = {'form':form_class}
    return render(request,'contact.html',context)

class UserFormView(View):
    form_class = UserForm
    template_name = 'registration_form.html'
    # display a blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})
    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            #cleaned (normalized) data

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #returns user objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('stores:index')
         # try again because it was not valid
        return render(request, self.template_name, {'form': form})

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                all_stores = Store.objects.filter(user=request.user)
                return render(request, 'index.html', {'all_stores': all_stores})
            else:
                return render(request, 'login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'login.html', {'error_message': 'Invalid login'})
    return render(request, 'login.html')

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'login.html', context)

stores/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stores</title>
    <!-- Loads the path to yur static files -->
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    
    <style>
     textarea { vertical-align: top; }
    </style>

</head>
<body>
    <nav class="navbar navbar-inverse">
   <div class="container-fluid">
      <!-- Header -->
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target = "#topNavBar">
             <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="{% url 'stores:index' %}">Stores&nbsp;&nbsp;&nbsp;</a>
<span STYLE="color: gray" class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
        <span STYLE="color: gray; font-family: 'Arial'; font-size: 10pt; line-height:50px">
          Hi {{ user.get_username }}!
        </span>

      </div>
       <!-- Items -->
       <div class="collapse navbar-collapse" id="topNavBar">
           <ul class="nav navbar-nav">
               <li class="">
                   <a href="{% url 'stores:index'  %}">
                       <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;
                       Stores
                   </a>
               </li>
               <li class="">
                <a href="{% url 'stores:products'  %}">
                    <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;
                    Products
                </a>
            </li>
           </ul>
           <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'stores:results' %}">
               <div class="form-group">
                   <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
               </div>
               <button type="submit" class="btn btn-default">Search Stores</button>
           </form>
           <ul class="nav navbar-nav navbar-right">
               <li class="">
                <a href="{% url 'stores:store-add' %}">
                  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                   Add Store
                </a>
               </li>
               <li class="">
                <a href="{% url 'stores:product-add' %}">
                  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                   Add Product
                </a>
               </li>
                <li class="">
                   <a href="{% url 'stores:contact' %}">
                       <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;
                       Contact us
                   </a>
              </li>

               <li class="">
                   <a href="{% url 'stores:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                       Logout
                   </a>
               </li>
           </ul>
       </div>
   </div>
</nav>
{%  block body %}
{% endblock %}
</body>
</html>

stores/templates/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <title>Stores</title>
    <!-- Loads the path to yur static files -->
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


</head>
<body>
    <nav class="navbar navbar-inverse">
   <div class="container-fluid">
      <!-- Header -->
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target = "#topNavBar">
             <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="{% url 'stores:index' %}">Stores</a>
      </div>
       <!-- Items -->
      <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'stores:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'stores:login_user' %}">Log In</a></li>
            </ul>
      </div>
   </div>
</nav>
{%  block body %}
{% endblock %}
</body>
</html>

stores/templates/contact.html
{% extends 'base.html' %}
{% block body %}
    <div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                 <h3>Contact us</h3>
                  <form class="form-horizontal" role="form" action="" method="post">
                   {% csrf_token %}
                   {{ form.as_p }}
                    <div class = 'form-group'>
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                   </form>
                </div>
            </div>
         </div>
    </div>
   </div>

{% endblock %}

stores/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid grades-container">

    <div class="row">

        <!-- Left Store Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="/stores/{{ my_store.id }}">
                        <img src="{{ my_store.store_pic.url }}" class="img-responsive">
                    </a>
                     <h4>{{ my_store.id }} </h4>
                     <h5>{{ my_store.description }} {{ my_store.address }}</h5>
                </div>
            </div>
        </div>
        <!-- Right Products Info -->
        <div class="col-sm-8 col-md-9">

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Products</h3>

                    <table class="table">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Description</th>
                            <th>Price</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for product in store_product %}
<tr>
                                <td>{{ product.id }}</td>
                                <td>{{ product.description }}</td>
                                <td>${{ product.price }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

stores/templates/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">
            {{ field }}
        </div>
    </div>
{% endfor %}

stores/templates/index.html
{% extends 'base.html' %}
{% block body %}
{% if all_stores %}
   <ul>
     {%for store in all_stores %}
         <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href= "/stores/{{ store.id}}">
                         <img src="{{ store.store_pic.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h4>StoreID: {{ store.id }} </h4>
                            <ul>
                                <li><h5>Description: {{ store.description }}</h5></li>
                                <li><h5>Address: {{ store.address }}</h5></li>
                            </ul>

                            <!-- View Details -->
                            <a href="/stores/{{store.id}}" class="btn btn-primary btn-sm" role="button">View Products</a>

                            <!-- Delete Store -->
                            <form action="{% url 'stores:store-delete' store.id %}" method="get" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="store_id" value="{{ student.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                            <!-- Update Store -->
                            <form action="{% url 'stores:store-update' store.id %}" method="get" style="display: inline;">
                                {% csrf_token %}
                              <input type="hidden" name="store_id" value="{{ store.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </button>
                            </form>


                        </div>
                    </div>
</div>
     {% endfor %}
   </ul>
{% else %}
   <h3> You don't have any stores</h3>
{% endif %}
{% endblock %}

stores/templates/login.html
{% extends 'base_visitor.html' %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'stores:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'stores:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

stores/templates/products.html
{% extends 'base.html' %}
{% block body %}
{% if all_products %}
   <ul>
     {%for product in all_products %}
         <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <div class="caption">
                            <h4>ProductID: {{ product.id }} </h4>
                            <h5>Description: {{ product.description }} Price: ${{ product.price }}</h5>

                            <!-- Delete Product -->
                            <form action="{% url 'stores:product-delete' product.id %}" method="get" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="store_id" value="{{ product.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <form action="{% url 'stores:product-update' product.id %}" method="get" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="store_id" value="{{ product.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </button>
                            </form>
                        </div>
                    </div>
</div>
     {% endfor %}
   </ul>
{% else %}
   <h3> You don't have any products</h3>
{% endif %}
{% endblock %}

stores/templates/registration_form.html
{% extends 'base_visitor.html' %}
{% block register_active %}active{% endblock %}
    {% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Create a New Account</h3>
                        <form class="form-horizontal" action ="" method = "post">
		     {% csrf_token %}
                            {% include 'form-template.html' %}
                            <div class = 'form-group'>
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}